import type { Metadata } from "next";
import "./globals.css";
import SmoothScroll from "@/modules/common/components/smooth-sroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased bg-white text-black"
    >
      <SmoothScroll>
        <body className="min-h-full flex flex-col">{children}</body>
      </SmoothScroll>
    </html>
  );
}
